"""Small fixes 2.0

Revision ID: b2b4c5db10d8
Revises: ecea4484eaa7
Create Date: 2026-09-01 13:01:29.636879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b4c5db10d8'
down_revision: Union[str, Sequence[str], None] = 'ecea4484eaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'active')
    # ### end Alembic commands ###
