services:
  objectdetector:
    image: photoview-tools/objectdetector
    build:
      context: .
      dockerfile: Dockerfile
      target: retinarcnn
    command: python3 /app/ScanPhotoviewWithMaskRCNN.py
    hostname: photoview-objectdetector
    container_name: photoview-objectdetector
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}"
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
    volumes:
      - ./app:/app:rw
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"

