FROM python:3.12-trixie AS labelme.python.local

RUN apt update && apt upgrade -y && apt install -y qtwayland5 xdg-utils dbus-x11 libxcb-cursor0 libxcb-glx0 libgl1-mesa-dev
RUN pip3 install --upgrade pip

ENV XDG_RUNTIME_DIR=/tmp/runtime-root
ENV XDG_SESSION_TYPE=wayland
ENV WAYLAND_DISPLAY=wayland-0
ENV QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
ENV QT_QPA_PLATFORM=wayland
RUN mkdir -p $XDG_RUNTIME_DIR

WORKDIR /app
COPY labelme /app/labelme
RUN pip3 install 'labelme>=7.0.4' labelme2coco
CMD labelme

#RUN pip3 install hatch
#RUN git clone https://github.com/wkentaro/labelme.git /app
#RUN hatch build -t wheel labelme
#RUN pip3 install labelme/labelme-7.0.*-py3-none-any.whl
                       # labelme-7.0.5.dev55+g73d25ef48-py3-none-any.whl
                       # labelme-7.0.3.................-py3-none-any.whl
#ENTRYPOINT hatch run labelme

ENV RUN_OPT_BASE="--json --image /app/labelme/0000-LAV_NRW_R_PA_3103_29568_0007.jpg"
ENV RUN_OPT_TEXT="{\"texts\": [\"cat\"]}"
ENV RUN_OPT_REGION="{\"points\": [[1439, 504], [1439, 1289]], \"point_labels\": [1, 1]}"
# AI-Assisted EfficientSam (speed)
RUN osam run efficientsam:10m  $RUN_OPT_BASE   > efficientsam-speed.txt
# AI-Assisted EfficientSam (accuracy)
RUN osam run efficientsam      $RUN_OPT_BASE   > efficientsam-accuracy.txt
# AI-Assisted Sam (speed)
RUN osam run sam:100m          $RUN_OPT_BASE   > sam-speed.txt
# AI-Assisted Sam (balanced)
RUN osam run sam:300m          $RUN_OPT_BASE   > sam-balanced.txt
# AI-Assisted Sam (accuracy)
RUN osam run sam               $RUN_OPT_BASE > sam-accuracy.txt
# AI-Assisted Sam2 (speed)            & 
RUN osam run sam2:small        --prompt "$RUN_OPT_REGION" $RUN_OPT_BASE > sam2-speed.txt
# AI-Assisted Sam2 (balanced)         & 
RUN osam run sam2              --prompt "$RUN_OPT_REGION" $RUN_OPT_BASE > sam2-balanced.txt
# AI-Assisted Sam2 (accuracy)         & 
#RUN osam run sam2:large        --prompt "$RUN_OPT_REGION" $RUN_OPT_BASE > sam2-accuracy.txt
#                                     & AI Text-to YOLO-World (fast)
#RUN osam run yoloworld         --prompt "$RUN_OPT_TEXT" $RUN_OPT_BASE > yolo.txt
# AI-Assisted Sam3                    & AI Text-to SAM3 (smart)
#RUN osam run sam3              --prompt "$RUN_OPT_TEXT" $RUN_OPT_BASE > sam3.txt

# docker run -it
#	 -v $(pwd):/root/workdir
#	 --volume="/run/user/1000/$WAYLAND_DISPLAY:/tmp/runtime-root/$WAYLAND_DISPLAY:rw"
##	 --volume="$HOME/.Xauthority:/root/.Xauthority:rw"
##	 -e "XDG_RUNTIME_DIR=/tmp/runtime-root"
##	 -e "WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
##	 -e "XDG_SESSION_TYPE=wayland"
#	 --privileged
#	 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

