services:
  objectdetector:
    image: photoview-tools/objectdetector-python
    build:
      context: .
      dockerfile: Dockerfile.torch-python
      target: retinarcnn-python
    command: python3 /app/ScanPhotoviewWithMaskRCNN.py
    privileged: true
    hostname: photoview-objectdetector-python
    container_name: photoview-objectdetector-python
    restart: Never # unless-stopped
    ports:
      - "80:80"
    environment:
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}"
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
      #XDG_RUNTIME_DIR: "/tmp/Wayland-runtime-root"
      #WAYLAND_DISPLAY: "wayland-0"
    volumes:
      - "/home/helmut/pod-dev/photoview-tools/app:/app:z"
      #- "/run/user/1000:$XDG_RUNTIME_DIR:z"
      #- "/run/user/1000/$WAYLAND_DISPLAY:/tmp/Wayland-runtime-root/$WAYLAND_DISPLAY:rw"
      - "/run/user/1000/wayland-0:/tmp/runtime-root/wayland-0:rw,z"
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "/home/helmut/pod-dev/photoview-tools/data/handwriting/orig:/handwriting/orig:ro"
      - "/home/helmut/pod-dev/photoview-tools/data/handwriting/generated:/handwriting/generated:rw"
      - "/home/helmut/pod-dev/photoview-tools/logs:/Mask-RCNN_model/logs:rw"
#      - "/home/helmut/pod-dev/photoview-tools/Mask-RCNN_TF2.14.0:/Mask-RCNN_model:rw"
#      - "./handwriting/generated:/handwriting/generated:rw"
      - "/home/helmut/Downloads/LAV:/app/LAV:rw"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.1.151/
#      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
      - '3000:3000'
    volumes:
      - '/home/helmut/pod-dev/photoview-tools/_container_graphana:/var/lib/grafana:rw,z'
      - "/home/helmut/pod-dev/photoview-tools/app:/var/lib/grafana/app:rw,z"
