#ARG BASE=python:3.12-trixie
ARG BASE=python:3.14-trixie
# requirements.txt failed for mariadb # ARG BASE=python:3.14-trixie
FROM ${BASE} AS retinarcnn-python-base

RUN apt update && apt upgrade -y
RUN apt install -y git mariadb-client python3-mariadb-connector libmariadb-dev-compat libmariadb3 # libmariadb-dev gcc mariadb-connector-c-devel python3-devel 
RUN pip3 install --upgrade pip

#    && dnf install -y mysql-selinux \

#COPY app /app
#COPY labelme /app/labelme
WORKDIR /app

FROM retinarcnn-python-base AS filescanner

RUN apt update && apt upgrade -y && apt install -y qtwayland5 xdg-utils dbus-x11 libxcb-cursor0 libxcb-glx0 libgl1-mesa-dev

COPY app/FastapiFilesServer.py app/alchemyFilesDB.py app/alchemyModelFiles.py app/progress.py app/requirements-scanner.txt /app/
RUN pip3 install -r requirements-scanner.txt

#FROM retinarcnn-python-base AS retinarcnn-python
#
#RUN git clone https://github.com/LoiusCypher/Mask-RCNN_TF2.14.0.git /Mask-RCNN_model
#
#RUN sed -i -e "s:np\.bool:bool:g" /Mask-RCNN_model/mrcnn/utils.py
#
#COPY app /app
#COPY labelme /app/labelme
#
#RUN pip3 install -r requirements.txt
#RUN pip3 install "labelme>=7.0.4" labelme2coco
#
#ENV XDG_RUNTIME_DIR=/tmp/runtime-root
#ENV XDG_SESSION_TYPE=wayland
#ENV WAYLAND_DISPLAY=wayland-0
#ENV QT_WAYLAND_SHELL_INTEGRATION=xdg-shell
#ENV QT_QPA_PLATFORM=wayland
#
#RUN mkdir -p $XDG_RUNTIME_DIR

