services:
  objectdetector:
    image: photoview-tools/objectdetector
    build:
      context: .
      dockerfile: Dockerfile
      target: retinarcnn
    command: python3 /app/ScanPhotoviewWithMaskRCNN.py
    privileged: true
    hostname: photoview-objectdetector
    container_name: photoview-objectdetector
    restart: Never # unless-stopped
    ports:
      - "80:80"
    environment:
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}"
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
      #XDG_RUNTIME_DIR: "/tmp/Wayland-runtime-root"
      #WAYLAND_DISPLAY: "wayland-0"
    volumes:
      - "/home/helmut/pod-dev/photoview-tools/app:/app:z"
      #- "/run/user/1000:$XDG_RUNTIME_DIR:z"
      #- "/run/user/1000/$WAYLAND_DISPLAY:/tmp/Wayland-runtime-root/$WAYLAND_DISPLAY:rw"
      - "/run/user/1000/wayland-0:/tmp/runtime-root/wayland-0:rw,z"
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
      - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "/home/helmut/pod-dev/photoview-tools/data/handwriting/orig:/handwriting/orig:ro"
      - "/home/helmut/pod-dev/photoview-tools/data/handwriting/generated:/handwriting/generated:rw"
      - "/home/helmut/pod-dev/photoview-tools/logs:/Mask-RCNN_model/logs:rw"
      - "/home/helmut/pod-dev/photoview-tools/Mask-RCNN_TF2.14.0:/Mask-RCNN_model:rw"
#      - "./handwriting/generated:/handwriting/generated:rw"
# LAV/LAV_NRW--Abt_Rheinland--PA_3103--29568/*.json

