services:

  filescanner:
    image: ghcr.io/loiuscypher/photoview-tools:main
    build:
      context: .
      dockerfile: Dockerfile.filescanner
      target: filescanner
    command: uv run --directory filescanner_fastapi fastapi run --host 0.0.0.0 --port 8080
    privileged: true
    hostname: filescanner
    container_name: filescanner
    #restart: Never # unless-stopped
    restart: no
    ports:
      # for FastAPI
      - "8080:8080"
    environment:
      CURR_HOSTNAME: "${HOSTNAME}"
      MARIADB_CONN: "${MARIADB_USER}:${MARIADB_PASSWORD}@192.168.2.227:3306"
    volumes:
#      - "/home/helmut/docker/photoview-tools/app:/app:z"
      #- "/run/user/1000:$XDG_RUNTIME_DIR:z"
      #- "/run/user/1000/$WAYLAND_DISPLAY:/tmp/Wayland-runtime-root/$WAYLAND_DISPLAY:rw"
#      - "/run/user/1000/wayland-0:/tmp/runtime-root/wayland-0:rw,z"
      - "/etc/localtime:/etc/localtime:ro" ## use local time from host
      - "/etc/timezone:/etc/timezone:ro"   ## use timezone from host
#      - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"
#      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
#      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos:ro"
#      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
#      - "/home/helmut/docker/photoview-tools/data/handwriting/orig:/handwriting/orig:ro"
#      - "/home/helmut/docker/photoview-tools/data/handwriting/generated:/handwriting/generated:rw"
#      - "/home/helmut/docker/photoview-tools/logs:/Mask-RCNN_model/logs:rw"
#      - "/home/helmut/docker/photoview-tools/Mask-RCNN_TF2.14.0:/Mask-RCNN_model:rw"
#      - "./handwriting/generated:/handwriting/generated:rw"
#      - "/home/helmut/Downloads/LAV:/app/LAV:rw"
      - "/:/host_fs:ro,z"

  filescanner_dev:
    extends: filescanner
    image: photoview-tools/filescanner
    volumes:
      - "/home/helmut/docker/photoview-tools/app:/app:z"
    profiles: [dev]
    command: uv run --directory filescanner_fastapi fastapi dev --host 0.0.0.0 --port 8080

