"""progress update

Revision ID: 2271d3848718
Revises: 92035a2321f7
Create Date: 2026-09-12 09:03:46.039731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import migration_types
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2271d3848718'
down_revision: Union[str, Sequence[str], None] = '92035a2321f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'for_removed_progress',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('actions', 'for_new_or_updated_progress',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('actions', 'add_missing_sha_progress',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'add_missing_sha_progress',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('actions', 'for_new_or_updated_progress',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('actions', 'for_removed_progress',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
