"""insert expected end time

Revision ID: e87545e70ade
Revises: 2271d3848718
Create Date: 2026-09-12 16:59:53.195872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import migration_types


# revision identifiers, used by Alembic.
revision: str = 'e87545e70ade'
down_revision: Union[str, Sequence[str], None] = '2271d3848718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
