"""convert date defaults to server side

Revision ID: 0fd8765a140a
Revises: cf8b1f680090
Create Date: 2026-09-17 00:25:53.230410

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0fd8765a140a'
down_revision: str | Sequence[str] | None = 'cf8b1f680090'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
