"""rework timestamp handling

Revision ID: 447c7fafa532
Revises: d5e5a3e277e5
Create Date: 2026-09-18 01:37:01.295990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import migration_types
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '447c7fafa532'
down_revision: Union[str, Sequence[str], None] = 'd5e5a3e277e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('actions', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('files', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('folders', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('folders', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('hosts', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('hosts', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ignores', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('ignores', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ignores', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ignores', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('hosts', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('hosts', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('folders', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('files', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('actions', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('actions', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
