"""Add action progress fields

Revision ID: 7319eac16958
Revises: e39ff86ea411
Create Date: 2026-09-11 22:45:16.797605

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7319eac16958'
down_revision: str | Sequence[str] | None = 'e39ff86ea411'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('for_removed_progress', sa.Float(), nullable=True))
    op.add_column('actions', sa.Column('for_new_or_updated_progress', sa.Float(), nullable=True))
    op.add_column('actions', sa.Column('add_missing_sha_progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'add_missing_sha_progress')
    op.drop_column('actions', 'for_new_or_updated_progress')
    op.drop_column('actions', 'for_removed_progress')
    # ### end Alembic commands ###
