"""No change

Revision ID: 92035a2321f7
Revises: 7319eac16958
Create Date: 2026-09-11 23:29:59.328936

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '92035a2321f7'
down_revision: str | Sequence[str] | None = '7319eac16958'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
