"""insert expected end time (really)

Revision ID: cf8b1f680090
Revises: e87545e70ade
Create Date: 2026-09-12 17:07:50.601305

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf8b1f680090'
down_revision: str | Sequence[str] | None = 'e87545e70ade'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('expected_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'expected_at')
    # ### end Alembic commands ###
