"""rework timestamp handling

Revision ID: d5e5a3e277e5
Revises: f21fe2bbc1da
Create Date: 2026-09-17 22:44:08.671083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import migration_types


# revision identifiers, used by Alembic.
revision: str = 'd5e5a3e277e5'
down_revision: Union[str, Sequence[str], None] = 'f21fe2bbc1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
