"""convert date defaults to server side 2

Revision ID: dd585b5873d5
Revises: 0fd8765a140a
Create Date: 2026-09-17 01:18:21.356938

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'dd585b5873d5'
down_revision: str | Sequence[str] | None = '0fd8765a140a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
