"""Initial DB

Revision ID: e39ff86ea411
Revises: 
Create Date: 2026-09-11 22:38:23.896797

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e39ff86ea411'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('ipv4', mysql.INET4(), nullable=True),
    sa.Column('ipv6', mysql.INET6(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('subtree', sa.String(length=750), nullable=True),
    sa.Column('for_removed', sa.Boolean(), nullable=True),
    sa.Column('for_new_or_updated', sa.Boolean(), nullable=True),
    sa.Column('add_missing_sha', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.String(length=750), nullable=False),
    sa.Column('path_hash', sa.String(length=64).with_variant(mysql.CHAR(length=64), 'mariadb'), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ignores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=True),
    sa.Column('path_pattern', sa.String(length=750), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('length', sa.BigInteger(), nullable=False),
    sa.Column('ctime_ns', sa.BigInteger(), nullable=False),
    sa.Column('mtime_ns', sa.BigInteger(), nullable=False),
    sa.Column('ctime', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('mtime', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('file_hash', sa.String(length=128).with_variant(mysql.CHAR(length=128), 'mariadb'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=False),
    sa.Column('deleted_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=3), 'mariadb'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('ignores')
    op.drop_table('folders')
    op.drop_table('actions')
    op.drop_table('hosts')
    # ### end Alembic commands ###
