"""insert expected end time

Revision ID: e87545e70ade
Revises: 2271d3848718
Create Date: 2026-09-12 16:59:53.195872

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'e87545e70ade'
down_revision: str | Sequence[str] | None = '2271d3848718'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
